2025-06-21 22:04:20,860 INFO: 成功发送音频文件: cambridge-9f9edb80-a2393de8-badce274-d65d3885-7580abe1.mp3, 大小: 7277 bytes [in D:\Projects\VocabularyTrainer\app.py:54]
2025-06-21 22:41:57,455 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:21]
2025-06-21 22:51:17,995 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-21 22:55:52,452 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-21 22:58:19,283 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-21 23:08:18,175 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-21 23:21:59,405 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-21 23:30:42,459 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-21 23:43:09,031 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-21 23:47:34,703 ERROR: Exception on /api/submit [POST] [in P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\VocabularyTrainer\app.py", line 101, in submit_answers
    cursor.execute(
sqlite3.OperationalError: no such table: ErrorLogs
2025-06-22 07:36:08,234 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 07:36:50,516 ERROR: Exception on /api/submit [POST] [in P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\conda_envs\VocabMVP\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\VocabularyTrainer\app.py", line 101, in submit_answers
    cursor.execute(
sqlite3.OperationalError: no such table: ErrorLogs
2025-06-22 07:42:51,710 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 07:42:53,362 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:08:25,029 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:08:25,551 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:10:02,096 INFO: 记录错误: 单词ID=1, 学生答案=fourteen [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 08:10:02,100 INFO: 记录错误: 单词ID=40, 学生答案=paradise [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 08:13:02,225 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:13:22,865 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:14:42,015 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:15:48,320 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:15:49,472 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:16:04,765 ERROR: 获取错误历史记录时出错: no such table: ErrorLogs [in D:\Projects\VocabularyTrainer\app.py:280]
2025-06-22 08:18:15,321 ERROR: 记录错误到ErrorLogs表失败: no such table: ErrorLogs [in D:\Projects\VocabularyTrainer\app.py:126]
2025-06-22 08:18:15,341 INFO: ErrorLogs表已创建 [in D:\Projects\VocabularyTrainer\app.py:142]
2025-06-22 08:18:15,343 INFO: 记录错误: 单词ID=56, 学生答案=interest [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 08:18:15,344 INFO: 记录错误: 单词ID=39, 学生答案=thersdads [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 08:21:31,345 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:25:22,518 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:25:48,617 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 08:25:49,121 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 13:13:45,655 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 13:13:49,669 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 13:43:25,712 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 13:43:26,670 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 13:44:40,084 INFO: 记录错误: 单词ID=32, 学生答案=actisaew [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 13:44:40,088 INFO: 记录错误: 单词ID=44, 学生答案=face [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 13:44:40,090 INFO: 记录错误: 单词ID=49, 学生答案=excellent [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 13:48:01,334 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 13:48:02,238 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 13:49:42,994 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 13:49:43,772 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 14:34:07,568 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 14:34:08,403 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 14:38:16,301 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 14:38:17,176 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 14:43:48,987 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 14:43:49,833 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 14:44:28,139 INFO: 记录错误: 单词ID=1621, 学生答案=inside [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 14:44:28,143 INFO: 记录错误: 单词ID=1581, 学生答案=eighteen [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 14:44:28,144 INFO: 记录错误: 单词ID=1586, 学生答案=beneficial [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 14:48:08,480 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 14:48:09,321 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 15:00:30,668 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 15:00:31,542 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 15:02:05,348 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 15:02:06,219 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 15:13:30,217 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 15:13:31,233 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 16:00:26,969 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 16:00:27,828 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 16:03:43,041 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 16:03:44,086 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 23:31:57,150 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 23:31:58,172 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 23:34:22,961 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 23:34:23,878 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:28]
2025-06-22 23:35:04,426 INFO: 记录错误: 单词ID=41, 学生答案= [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 23:35:04,429 INFO: 记录错误: 单词ID=29, 学生答案=waste [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 23:35:04,433 INFO: 记录错误: 单词ID=35, 学生答案=silent [in D:\Projects\VocabularyTrainer\app.py:124]
2025-06-22 23:38:02,836 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
2025-06-22 23:39:09,399 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
2025-06-22 23:39:10,342 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
2025-06-22 23:42:26,608 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
2025-06-22 23:42:27,584 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
2025-06-22 23:43:05,958 INFO: 记录错误: 单词ID=35, 学生答案=silent [in D:\Projects\VocabularyTrainer\app.py:125]
2025-06-22 23:43:05,969 INFO: 记录错误: 单词ID=29, 学生答案=waste [in D:\Projects\VocabularyTrainer\app.py:125]
2025-06-22 23:48:02,110 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
2025-06-22 23:48:03,093 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
2025-06-22 23:48:42,735 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
2025-06-23 00:02:18,694 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
2025-06-23 00:02:19,680 INFO: 应用启动 [in D:\Projects\VocabularyTrainer\app.py:29]
